{
 "title": "SNMP Network Device Monitoring",
 "description": "Monitoring Network Devices  using SNMPv3",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "Host",
    "label": "IP Address",
    "query": "SHOW TAG VALUES FROM snmp WITH KEY=agent_host"
   }
  ]
 },
 "panels": [
  {
   "title": "IP Address",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT * FROM \"snmp\" WHERE (\"agent_host\" =~ /^$Host$/)"
    }
   ]
  },
  {
   "title": "System Status",
   "type": "stat",
   "gridPos": { "h": 10, "w": 10, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT \"result_code\" FROM \"ping\" WHERE (\"url\" =~ /^$Host$/) \n"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "allValues" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "snmp",
     "query": "SELECT last(\"uptime\")  / 100 FROM \"snmp\" WHERE (\"agent_host\" =~ /^$Host$/) AND time > now() - 2m",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "time", "operator": ">", "value": "now() - 2m" }
     ]
    }
   ]
  },
  {
   "title": "SNMP Device Room",
   "type": "stat",
   "gridPos": { "h": 4, "w": 10, "x": 14, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"gebaeude\" FROM \"snmp\" WHERE (\"agent_host\" =~ /^$Host$/)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Interfaces",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "ifName" ], "type": "tag" },
      { "params": [ "ifAlias" ], "type": "tag" },
      { "params": [ "ifOperStatusCause" ], "type": "tag" }
     ],
     "measurement": "IF",
     "query": "SELECT last(\"ifAdminStatus\") AS \"AdminStatus\", last(\"ifOperStatus\") AS \"OperStatus\", last(\"ifHighSpeed\") AS \"Speed\" FROM \"DATA\" WHERE (\"agent_host\" =~ /^$Host$/ ) AND time > now() -2m GROUP BY \"ifName\", \"ifAlias\", \"ifOperStatusCause\"",
     "select": [
      [
       { "params": [ "ifAdminStatus" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "AdminStatus" ], "type": "alias" }
      ],
      [
       { "params": [ "ifOperStatus" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "OperStatus" ], "type": "alias" }
      ],
      [
       { "params": [ "ifHighSpeed" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Speed" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "ifName", "operator": "=~", "value": "/^$ifName$/" }
     ]
    }
   ]
  }
 ]
}